dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: consul://localhost:8500
  consumer:
    check: false
    timeout: 3000
    retries: 2
    loadbalance: roundrobin
  provider:
    timeout: 3000
    retries: 2
    loadbalance: roundrobin
    threads: 200
    threadpool: cached

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
      compression:
        request:
          enabled: true
        response:
          enabled: true
    loadbalancer:
      ribbon:
        enabled: false
      retry:
        enabled: true
      cache:
        enabled: false 